//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ban_quan_ao_asp.net_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public string MaDanhGia { get; set; }
        public string MaSanPham { get; set; }
        public int DiemDanhGia { get; set; }
        public string NDDanhGia { get; set; }
        public string NDPhanHoi { get; set; }
        public string MaNguoiDung { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
