//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ban_quan_ao_asp.net_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.PhanLoaiMSSPs = new HashSet<PhanLoaiMSSP>();
            this.DanhGias = new HashSet<DanhGia>();
        }
    
        public string MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public decimal GiaNhap { get; set; }
        public decimal GiaBan { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string MoTaNgan { get; set; }
        public string AnhDaiDien { get; set; }
        public Nullable<bool> NoiBat { get; set; }
        public string MaPhanLoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanLoaiMSSP> PhanLoaiMSSPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual PhanLoai PhanLoai { get; set; }
    }
}
